---
abstract: 'Use `backticks` like objects!'
author:
  - 'Anthony Kilna <anthony@kilna.com>'
build_requires:
  Test::More: 0
  Time::HiRes: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Backticks
provides:
  Backticks:
    file: lib/Backticks.pm
    version: v1.0.6
requires:
  Carp: 0
  Class::ISA: 0
  Filter::Simple: 0
  IPC::Open3: 0
  Scalar::Util: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: v1.0.6
