---
abstract: 'Use `backticks` like objects!'
author:
  - 'Anthony Kilna <anthony@kilna.com>'
build_requires:
  Capture::Tiny: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.4'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Backticks
provides:
  Backticks:
    file: lib/Backticks.pm
    version: v1.9.0_2
requires:
  Filter::Simple: '0'
  Scalar::Util: '0'
  Scope::Upper: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
version: v1.9.0_02
